### ISSUE TITLE
0.8.42 regression: standalone model to_xml crashes (register_id mismatch in RuleCompiler — 'undefined method [] for nil' / 'transform for nil'); parse +1.27x is real

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-model#815]
## 0.8.42 regression: standalone model serialization crashes (`undefined method '[]' for nil` / `transform for nil`) — register_id mismatch in RuleCompiler

The 0.8.42 compiled-rules work (#811's ask — thank you, the speedup is real and measured below) breaks serializing a model **as its own document root**. Consumer suite: 38 failures, all on standalone `to_xml` paths; parsing and parent-driven serialization are unaffected.

### Minimal reproduction

```ruby
require "lutaml/model" # any consumer tree; uniword's models below

class Para < Lutaml::Model::Serializable  # or any real consumer model
  # ... attributes + xml mapping with a register
end

Para.new.to_xml
# NoMethodError: undefined method '[]' for nil
```

Verified concretely with uniword:

```ruby
require "uniword"
Uniword::Wordprocessingml::Paragraph.new.to_xml
# => NoMethodError: undefined method '[]' for nil
```

### Signature 1 — `compile_element_rule`

```
NoMethodError: undefined method '[]' for nil
  lib/lutaml/model/serialize/initialization.rb:136  # @register_records[register_id][:attributes]
  lib/lutaml/xml/transformation/rule_compiler.rb:103 # compile_element_rule
  lib/lutaml/xml/transformation/rule_compiler.rb:30/31
  lib/lutaml/xml/transformation.rb:135
  lib/lutaml/model/transformation.rb:39
  lib/lutaml/xml/transformation_builder.rb:24
  lib/lutaml/model/transformation_registry.rb:296   # build_transformation
```

`initialization.rb` around the crash: with `@register_records` non-empty, `@merged_attributes_cache[register_id] ||= @register_records[register_id][:attributes]` — the incoming `register_id` from `RuleCompiler` has **no entry** in the model's `@register_records` (our models carry `@lutaml_register = :uniword`), so the inner `[:attributes]` is called on nil. Register-id resolution between `RuleCompiler#compile_rules` and the class's registered records is mismatched on this path.

### Signature 2 — serializer

```
NoMethodError: undefined method 'transform' for nil
  lib/lutaml/xml/adapter/xml_serializer.rb:152 # transformable_xml_element
  ... to_xml chain
```

Likely the same root (transformation lookup returning nil for a class on the standalone path).

### Impact vs. payoff

- Parse (hydration) is **fine and ~1.27× faster** on 0.8.42 (clean interleaved A/B vs 0.8.40: 8.0 s → 6.3 s CPU, 608 KB corpus) — the dispatch hoisting works.
- Serialization of standalone models (specs, part-level writers, any `SomeModel.new.to_xml`) crashes — for uniword that is 38 spec failures across line_spacing, paragraph round-trips, theme schemes, w14 paraId, and more.

### Environment

ruby 3.4.8, lutaml-model 0.8.41/0.8.42 (0.8.40 unaffected), moxml 0.5.65 adapter stack; repro requires no fixtures.

Happy to re-verify immediately against a patch — the consumer suite exercises both signatures densely.

**Comment by ronaldtse** [comment]
Diagnosed and fixed — **PR #817**.

**It is a 0.8.42 regression** (bisected: v0.8.40 OK, v0.8.41 OK, v0.8.42 crashes; introduced by #813), and the root cause is not a register-id mismatch. #813's `attributes()` reorder materializes `@merged_attributes_cache` **before** `ensure_imports!`, but the ensure pass can re-entrantly run `clear_cache` (choice/restrict/import resolution), which sets `@merged_attributes_cache = nil` — the memo write after the ensure then called `nil[]`. 0.8.41's ensure-first order happened to tolerate the mid-ensure clear.

Verified against your report's exact repro (`Uniword::Wordprocessingml::Paragraph.new.to_xml` now emits `<p xmlns=…>`) and a sweep of all 197 Serializable classes in the uniword tree standalone: 176 serialize, 21 refuse with the correct `TypeOnlyMappingError` (type-only models) — both crash signatures gone. The new spec reproduces on v0.8.42 and passes on the fix.

A patch release follows once #817's CI is green — thanks for the superb report, and glad the +1.27x parse held up.

**Comment by ronaldtse** [comment]
Verified on the released 0.8.43:

- Both signatures from the report are gone: standalone `Paragraph.new.to_xml` and full-document serialization both succeed; the 38 consumer failures clear to **1589 examples / 0 failures** (wordprocessingml + ooxml + validation + redact + find_replace + caption + docx_roundtrip + docx suites, single pass).
- Bonus measured in the same pass: the allocation-diet tranche (#811 follow-up) lands too — **4.6 M → 3.8 M allocations per parse (−17%)**, with hydration CPU at ~6.1 s vs ~8.3 s on 0.8.40 (interleaved A/B, same session).

Thanks for the fast turnaround — closing our loop.
